title: 天門冬の庭
author: Asparagaliz Lily
email: asparagaliz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Asparagales blooming here and Asaparagaliz sitting here.
baseurl: "/jekyll-theme-kagami"
lang: ja # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: asparagaliz
twitter_username: asparagaliz
instagram_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
